---
title: "R Notebook"
output: html_notebook
---
##Filtering: Selecting CMV and MEM Data Aligned with Rat-Mouse Genome Combination
 
# rat merged 
 
```{r}
print("Colnames CMV_rat:")
head(colnames(CMV_rat))
print("Colnames MEM_rat:")
head(colnames(MEM_rat))
print("head colnames Object to filter on:")
head(colnames(rat_merged))
print("Condition of Object to filter on:")
head(rat_merged$orig.ident)
print("tail Colnames Object to filter on:")
tail(colnames(rat_merged))
print("Condition of Object to filter on:")
tail(rat_merged$orig.ident)
```

```{r}
# Filter CMV_rat and MEM_rat based on seurt_aligned_rat_mouse

# CMV_rat based on -1_1 in seurat_aligned_rat_mouse
CMV_Filters <- grep("-1_1", colnames(rat_merged), value= T)
CMV_Filters <- sub("_1","",CMV_Filters)
# MEM_rat based on -1_2 in seurat_aligned_rat_mouse
MEM_Filters <- grep("-1_2", colnames(rat_merged), value = T)
MEM_Filters <- sub("_2","",MEM_Filters)
```

```{r}
# Subset the CMV_rat Seurat object based on -1_1 in seurat_aligned_rat_mouse
seurat_aligned_rat_CMV <- CMV_rat[, CMV_Filters]

# Subset the MEM_rat Seurat object based on -1_2 in seurat_aligned_rat_mouse
seurat_aligned_rat_MEM <- MEM_rat[, MEM_Filters]
```
