---
title: "R Notebook"
output: html_notebook
---
##Selecting Clusters for PCA, UMAP and PHATE Embeddingq
 
```{r}
# Select the clusters based on the desire identities
clusters_toPLot <- c("0","1","2","3","4","6","7","8","9","10","14","15")
# Subset the aligned_rat_merged_subcluster object to include only the selected clusters
new_clustertoPLot <- subset(aligned_rat_merged, idents =  clusters_toPLot)
# Normalize the data in the new_clustertoPlot object
new_clustertoPLot <- NormalizeData(new_clustertoPLot, verbose = F)
# Scale the data in the new_clustertoPlot object
new_clustertoPLot <- ScaleData(new_clustertoPLot, verbose = F)
# Run PCA on the new_clustertoPlot object with 50 principal components
new_clustertoPLot <- RunPCA(new_clustertoPLot, npcs = 50, verbose = F)
# Run UMAP on the new_clustertoPlot object using the PCA embeddings and the first 50 dimensions
new_clustertoPLot<- RunUMAP(new_clustertoPLot, reduction = "pca", dims = 1:50, verbose = F)
# Perform PHATE dimensionality reduction on the PCA embeddings of the new_clustertoPlot object
data_new_clustertoPLot<- phate(new_clustertoPLot@reductions$pca@cell.embeddings)
# Store the PHATE embeddings as a dimension reduction object within the new_clustertoPlot object
new_clustertoPLot[["PHATE"]] <- CreateDimReducObject(embeddings = data_new_clustertoPLot$embedding, key = "PHATE_", assay = DefaultAssay(new_clustertoPLot))
```

```{r}
# Define a named vector with cluster-color mappings
color_Palette <- c(
  "0" <- "#FF8080",    # Medium-light red
  "1" <- "#80B3FF",    # Medium-light blue
  "2" <- "#80FF80",    # Medium-light green
  "3" <- "#FFCC40",    # Medium-light orange
  "4" <- "#D9B3FF",    # Medium-light purple
  "6" <- "#99FFFF",    # Medium-light cyan
  "7" <- "#FF80FF",    # Medium-light magenta
  "8" <- "#80FF80",    # Medium-light green
  "9" <- "#E69966",    # Medium-light brown
  "10" <- "#FFB3D9",   # Medium-light pink
  "14" <- "#FFB380",   # Medium-light orange
  "15" <- "#FFD633"    # Medium-light gold
)
#Sort the clusters in the following order
new_order <- c("0","1","2","3","4","6","7","8","9","10","14","15")
# Assign the new order to the "seurat_clusters" factor variable in the new_clustertoPLot object
new_clustertoPLot$seurat_clusters <- factor(x = Idents(aligned_rat_merged), levels = new_order)
# Plot with cluster labels and specific color palette
DimPlot(new_clustertoPLot, reduction = "umap", label = T) +
  scale_color_manual(values = color_Palette,  guide = FALSE) +
  ggtitle("UMAP")

```


```{r}
aligned_rat_merged <- SetIdent(aligned_rat_merged, value = aligned_rat_merged$sub.clusters)
# Define a named vector with cluster-color mappings
color_Palette2 <- c(
  "0" <- "#FF8080",    # Medium-light red
  "1" <- "#80B3FF",    # Medium-light blue
  "2" <- "#80FF80",    # Medium-light green
  "3" <- "#FFCC40",    # Medium-light orange
  "4" <- "#D9B3FF",    # Medium-light purple
  "6" <- "#99FFFF",    # Medium-light cyan
  "8" <- "#80FF80",    # Medium-light green
  "9" <- "#E69966",    # Medium-light brown
  "10" <- "#FFB3D9",   # Medium-light pink
  "14" <- "#FFB380",   # Medium-light orange
  "15" <- "#FFD633",    # Medium-light gold
  "7_0" <- "#FF80FF",  # Custom color for cluster 7_0
  "7_1" <- "#00FFFF",  # Custom color for cluster 7_1
  "7_2" <- "#FFB6C1",  # Custom color for cluster 7_2
  "7_3" <- "#008080"  # Custom color for cluster 7_3
)
#Sort the clusters in the following order
new_order <- c("0","1","2","3","4","5","6","8","9","10","11","12","13","14","15","7_0","7_1","7_2","7_3")
# Assign the new order to the "seurat_clusters" factor variable in the new_clustertoPLot object
new_clustertoPLot$sub.clusters <- factor(x = Idents(aligned_rat_merged), levels = new_order)
# Plot with cluster labels and specific color palette
DimPlot(new_clustertoPLot, reduction = "umap", group.by = "sub.clusters", label = T) + 
  scale_color_manual(values = color_Palette2, guide = FALSE) +
  ggtitle("UMAP with sub-clusters")
```


```{r} 
# Create A PHATE embedding plot for the selected clusters
DimPlot(new_clustertoPLot, reduction = "PHATE",   label = T  ) +
  scale_color_manual(values = color_Palette, guide = FALSE) +
  ggtitle(label = "PHATE")
```

```{r}
#Create A PHATE embedding plot for the selected clusters with sub_clustering cluster 7
DimPlot(new_clustertoPLot, reduction = "PHATE", group.by = "sub.clusters",label = T  ) +
  scale_color_manual(values = color_Palette2, guide = FALSE) +
  ggtitle(label = "PHATE with sub-clusters")

```

```{r}

#saveRDS(new_clustertoPLot, file = "S:/Mcyto/Experiments/R&D/2023/Adel-cmv_scRNAseq/selected_cluster_phate_umap.rds")
```

