---
title: "R Notebook"
output: html_notebook
---

 

```{r}
# Find markers specific to cluster "7_0" in the aligned_rat_merged object
cluster7_0.markers <- FindMarkers(aligned_rat_merged , ident.1 =   "7_0", logfc.threshold = 0.25, min.pct = 0.25)
# Filter the markers based on adjusted p-value (p_val_adj)
cluster7_0.markers <- cluster7_0.markers[cluster7_0.markers$p_val_adj<0.05,]
# Filter the markers to include only positive average log fold change (avg_log2FC)
cluster_7_0.markers.only_pos <- cluster7_0.markers[cluster7_0.markers$avg_log2FC>0,]
# Filter the markers to include only negative average log fold change (avg_log2FC)
cluster_7_0.markers.only_negative <- cluster7_0.markers[cluster7_0.markers$avg_log2FC<0,]

```

```{r}
# Find markers specific to cluster "7_1" in the aligned_rat_merged object
cluster7_1.markers <- FindMarkers(aligned_rat_mergedr , ident.1 =   "7_1", logfc.threshold = 0.25, min.pct = 0.25)
# Filter the markers based on adjusted p-value (p_val_adj)
cluster7_1.markers <- cluster7_1.markers[cluster7_1.markers$p_val_adj<0.05,]
# Filter the markers to include only positive average log fold change (avg_log2FC)
cluster_7_1.markers.only_pos <- cluster7_1.markers[cluster7_1.markers$avg_log2FC>0,]
# Filter the markers to include only negative average log fold change (avg_log2FC)
cluster_7_1.markers.only_negative <- cluster7_1.markers[cluster7_1.markers$avg_log2FC<0,]

```

```{r}
# Find markers specific to cluster "7_2" in the aligned_rat_merged object
cluster7_2.markers <- FindMarkers(aligned_rat_merged , ident.1 =   "7_2", logfc.threshold = 0.25, min.pct = 0.25)
# Filter the markers based on adjusted p-value (p_val_adj
cluster7_2.markers <- cluster7_2.markers[cluster7_2.markers$p_val_adj<0.05,]
# Filter the markers to include only positive average log fold change (avg_log2FC)
cluster_7_2.markers.only_pos <- cluster7_2.markers[cluster7_2.markers$avg_log2FC>0,]
# Filter the markers to include only negative average log fold change (avg_log2FC)
cluster_7_2.markers.only_negative <- cluster7_2.markers[cluster7_2.markers$avg_log2FC<0,]

```

```{r}
# Find markers specific to cluster "7_3" in the aligned_rat_merged object
cluster7_3.markers <- FindMarkers(aligned_rat_merged , ident.1 =   "7_3", logfc.threshold = 0.25, min.pct = 0.25)
# Filter the markers based on adjusted p-value (p_val_adj
cluster7_3.markers <- cluster7_3.markers[cluster7_3.markers$p_val_adj<0.05,]
# Filter the markers to include only positive average log fold change (avg_log2FC)
cluster_7_3.markers.only_pos <- cluster7_3.markers[cluster7_3.markers$avg_log2FC>0,]
# Filter the markers to include only negative average log fold change (avg_log2FC)
cluster_7_3.markers.only_negative <- cluster7_3.markers[cluster7_3.markers$avg_log2FC<0,]

```
